const clockEl=document.getElementById('clock'),timeInput=document.getElementById('timeInput'),labelInput=document.getElementById('labelInput'),setBtn=document.getElementById('setBtn'),alarmListEl=document.getElementById('alarmList'),permissionBtn=document.getElementById('permissionBtn'),statusEl=document.getElementById('status'),alarmSound=document.getElementById('alarmSound');
let alarms=JSON.parse(localStorage.getItem('alarms')||'[]');
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js');
permissionBtn.onclick=async()=>{const r=await Notification.requestPermission();statusEl.textContent=r==='granted'?'✅ Notifikasi aktif':'❌ Ditolak'};
setInterval(()=>{clockEl.textContent=new Date().toLocaleTimeString('id-ID',{hour12:false});if(new Date().getSeconds()===0)check()},1000);
setBtn.onclick=async()=>{if(!timeInput.value)return alert('Pilih jam');if(Notification.permission!=='granted')await Notification.requestPermission();alarms.push({id:Date.now(),time:timeInput.value,label:labelInput.value||'Alarm',active:true});save()};
function save(){localStorage.setItem('alarms',JSON.stringify(alarms));render()}
function render(){alarmListEl.innerHTML='';alarms.forEach(a=>{const li=document.createElement('li');li.innerHTML=`<div><b>${a.time}</b><br><small>${a.label}</small></div><div><button onclick="toggle(${a.id})">${a.active?'Off':'On'}</button><button onclick="hapus(${a.id})" style="background:#ef4444;margin-left:5px">X</button></div>`;alarmListEl.appendChild(li)})}
window.toggle=id=>{alarms=alarms.map(a=>a.id===id?{...a,active:!a.active}:a);save()};window.hapus=id=>{alarms=alarms.filter(a=>a.id!==id);save()};
function check(){const cur=new Date().toTimeString().slice(0,5);alarms.forEach(a=>{if(a.active&&a.time===cur)trigger(a)})}
function trigger(alarm){alarmSound.currentTime=0;alarmSound.play().catch(()=>{});setTimeout(()=>{alarmSound.pause()},5000);if(navigator.vibrate){navigator.vibrate([500,200,500]);setTimeout(()=>navigator.vibrate(0),5000)};if(navigator.serviceWorker.controller){navigator.serviceWorker.controller.postMessage({type:'ALARM_TRIGGER',time:alarm.time,label:alarm.label})}statusEl.textContent=`🔔 ${alarm.label} - berhenti otomatis 5 detik`}
render();